version: "3.9"

services:
  local-backend:
    image: ghcr.io/bookpanda/mygraderlist-backend:dev
    container_name: backend
    restart: unless-stopped
    networks:
      - mgl-local
      - database
    volumes:
      - ./service/local/backend:/app/config
    ports:
      - "3001:3001"

  local-db:
    image: mysql:8.0.28-oracle
    container_name: local-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mgl-db
    networks:
      - database
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  local-cache:
    image: bitnami/redis:6.2.6
    container_name: local-cache
    restart: unless-stopped
    environment:
      REDIS_HOST: localhost
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - database
    ports:
      - "6379:6379"


networks:
  rnkm-local:
    name: mgl-local
  database:
    name: database
