version: "3.9"

services:
  local-backend:
    image: ghcr.io/bookpanda/mygraderlist-backend
    platform: linux/amd64
    container_name: backend
    depends_on:
      - local-db
      - local-cache
    restart: unless-stopped
    networks:
      - mgl-local
      - database
    volumes:
      - ./service/local/backend:/app/config
    ports:
      - "3001:3001"

  local-auth:
    image: ghcr.io/bookpanda/mygraderlist-auth
    platform: linux/amd64
    container_name: auth
    depends_on:
      - local-db
      - local-cache
    restart: unless-stopped
    networks:
      - mgl-local
      - database
    volumes:
      - ./service/local/auth:/app/config
    ports:
      - "3002:3002"

  local-db:
    image: mysql:8.0.28-oracle
    container_name: local-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mgl-db
    networks:
      - database
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  local-cache:
    image: redis:alpine
    container_name: local-cache
    restart: unless-stopped
    environment:
      REDIS_HOST: localhost
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - database
    ports:
      - "6379:6379"


networks:
  mgl-local:
    name: mgl-local
  database:
    name: database

volumes:
  mysql_data:
