redis:
  host: local-cache:6379
  password: ""

database:
  host: local-db
  port: 3306
  name: mgldb
  username: root
  password: root

app:
  port: 3002
  debug: true
  secret: <secret>

service:
  backend: backend:3003

jwt:
  secret: <secret>
  expires_in: 3600
  issuer: https://mygraderlist.bookpanda.dev

google-oauth:
  client_id:    <client_id>
  client_secret: <client_secret>
  redirect_uri:  http://localhost:3001
